apiVersion: apps/v1
kind: Deployment
metadata:
  name: manager
  labels:
    app: manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: manager
  template:
    metadata:
      labels:
        app: manager
    spec:
      containers:
      - name: manager
        image: ghcr.io/platform-engineering-org/afula-manager:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
        env:
          - name: DATABASE_URL
            value: postgresql://myuser:mypassword@postgres:5432/mydb
---
apiVersion: v1
kind: Service
metadata:
  name: manager
spec:
  selector:
    app: manager
  ports:
  - port: 5000
    targetPort: 5000
  type: ClusterIP
