apiVersion: apps/v1
kind: Deployment
metadata:
  name: afula
  labels:
    app: afula
spec:
  replicas: 1
  selector:
    matchLabels:
      app: afula
  template:
    metadata:
      labels:
        app: afula
    spec:
      containers:
      - name: afula
        image: ghcr.io/platform-engineering-org/afula:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
        env:
          - name: DATABASE_URL
            value: postgresql://myuser:mypassword@postgres:5432/mydb
---
apiVersion: v1
kind: Service
metadata:
  name: afula
spec:
  selector:
    app: afula
  ports:
  - port: 5000
    targetPort: 5000
  type: ClusterIP
