apiVersion: apps/v1
kind: Deployment
metadata:
  name: afula-app
  labels:
    app: afula-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: afula-app
  template:
    metadata:
      labels:
        app: afula-app
    spec:
      containers:
      - name: afula-app
        image: ghcr.io/platform-engineering-org/afula:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
          requests:
            memory: "128Mi"
            cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: afula-app-service
spec:
  selector:
    app: afula-app
  ports:
  - port: 5000
    targetPort: 5000
  type: ClusterIP
